<a class="anchor" id="Part 1"></a>

# Part 1

In [37]:
%pylab inline

%pylab is deprecated, use %matplotlib inline and import the required libraries.
Populating the interactive namespace from numpy and matplotlib


<a class="anchor" id="Creating 2D Arrays"></a>

## Creating 2D Arrays

In [36]:
#Making a linearly spaced numbers for y_hat
y_hat = linspace(-1, 1, 20)
y_hat

array([-1.        , -0.89473684, -0.78947368, -0.68421053, -0.57894737,
       -0.47368421, -0.36842105, -0.26315789, -0.15789474, -0.05263158,
        0.05263158,  0.15789474,  0.26315789,  0.36842105,  0.47368421,
        0.57894737,  0.68421053,  0.78947368,  0.89473684,  1.        ])

In [40]:
#Making a linearly spaced numbers for y
y = linspace(0, 1, 20)
y

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [53]:
#Making a logarithmically spaced numbers for y_hat
y_hat = np.logspace (-1,1,20)
logy_hat = y_hat
log_y_hat

array([ 0.1       ,  0.1274275 ,  0.16237767,  0.20691381,  0.26366509,
        0.33598183,  0.42813324,  0.54555948,  0.6951928 ,  0.88586679,
        1.12883789,  1.43844989,  1.83298071,  2.33572147,  2.97635144,
        3.79269019,  4.83293024,  6.15848211,  7.8475997 , 10.        ])

In [57]:
#Making a logarithmically spaced numbers for y
y = logspace (0,1,20)
log_y = y
log_y

array([ 1.        ,  1.12883789,  1.27427499,  1.43844989,  1.62377674,
        1.83298071,  2.06913808,  2.33572147,  2.6366509 ,  2.97635144,
        3.35981829,  3.79269019,  4.2813324 ,  4.83293024,  5.45559478,
        6.15848211,  6.95192796,  7.8475997 ,  8.8586679 , 10.        ])

In [13]:
#Reshaping y_hat into a 5x4 matrix 
a = y_hat.reshape(5,4)
a

array([[-1.        , -0.89473684, -0.78947368, -0.68421053],
       [-0.57894737, -0.47368421, -0.36842105, -0.26315789],
       [-0.15789474, -0.05263158,  0.05263158,  0.15789474],
       [ 0.26315789,  0.36842105,  0.47368421,  0.57894737],
       [ 0.68421053,  0.78947368,  0.89473684,  1.        ]])

In [70]:
#Dimension of y_hat
y_hat.ndim

1

In [71]:
#Shape of y_hat
y_hat.shape

(20,)

In [18]:
#Dimension of y
y.ndim

1

In [16]:
#Shape of y
y.shape

(20,)

In [17]:
#Reshaping y into a 5x4 matrix 
b = y.reshape(5,4)
b

array([[0.        , 0.05263158, 0.10526316, 0.15789474],
       [0.21052632, 0.26315789, 0.31578947, 0.36842105],
       [0.42105263, 0.47368421, 0.52631579, 0.57894737],
       [0.63157895, 0.68421053, 0.73684211, 0.78947368],
       [0.84210526, 0.89473684, 0.94736842, 1.        ]])

<a class="anchor" id="Mean Squared Error"></a>


## Mean Squared Error


In [27]:
#Computing for Mean Squared Error
def mean_squared_error(act, pred):

   diff = pred - act
   differences_squared = diff ** 2
   mean_diff = differences_squared.mean()
   
   return mean_diff

act = y_hat
pred = y

print(mean_squared_error(act,pred))

0.3421052631578948


<a class="anchor" id="Mean Absolute Error"></a>


## Mean Absolute Error


In [25]:
#Mean Absolute Error
def mean_absolute_error(act, pred):
    diff = pred - act
    abs_diff = np.absolute(diff)
    mean_diff = abs_diff.mean()
    return mean_diff

act = y_hat
pred = y
mean_absolute_error(act,pred)

0.4999999999999999

<a class="anchor" id="Mean Squared Logarithmic Error"></a>


## Mean Squared Logarithmic Error


In [60]:
#Mean Squared Logarithmic Error
def mean_squared_log_error(act, pred):

    diff = pred - act
    differences_squared = diff ** 2
    mean_diff = differences_squared.mean()
    return mean_diff

act = log_y_hat
pred = log_y

print(mean_squared_log_error(act,pred))

3.277651867667945


<a class="anchor" id="Mean Absolute Percentage Error"></a>


## Mean Absolute Percentage Error


In [61]:
#Mean Absolute Percentage Error
def mean_absolute_percentage_error(act, pred):
    diff = pred - act
    abs_diff = np.absolute(diff)
    mean_diff = abs_diff.mean()*100
    return mean_diff

act = y_hat
pred = y
mean_absolute_percentage_error(act,pred)

168.80031916553312

<a class="anchor" id="Part 2"></a>

# Part 2

## Making a 1D Array

In [66]:
#Making a 1D Array using arange function
M = np.arange(1,17)
M

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [67]:
#Shape of M
M.shape

(16,)

## Reshaping the Array into a 4x4 matrix

In [69]:
#Reshaping M into a 4x4 matrix
N = M.reshape (4,4)
N

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
#Get the 2nd row of N
N[1:2]

array([[5, 6, 7, 8]])

## Getting the Minimum Values

In [79]:
#Get the min for each column of N
np.min(N, axis = 0)

array([1, 2, 3, 4])

## Getting the locations of the Minimum Values

In [82]:
#Get the locations of the min values for each column of N
np.argmin(N, axis=0)

array([0, 0, 0, 0], dtype=int64)

## Getting the Average

In [83]:
#Get the average of the whole matrix
np.mean(N)

8.5

## Creating a Vector

In [99]:
#Creating a vector with 1 on each element
V = np.ones((4), dtype = 'int32')
V

array([1, 1, 1, 1])

## Dot Product of N and V

In [100]:
#Dot product of N and V
np.dot(N, V)

array([10, 26, 42, 58])